# Generated by Django 4.2.5 on 2023-10-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_profile_slug_alter_profile_email_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat/profile/', verbose_name='Аватар'),
        ),
    ]
